### ISSUE TITLE
Trying to add a virtual directory to a website

### ISSUE THREAD

**Issue by armplinker** [jexuswebserver/JexusManager#127]
I was trying to add the Crystal Reports viewer to an existing website using this tool and it blew up.  I have no clue what I did.

13.0.0.18 on Windows 10 Home (1903) with .NET Framework Version: 4.8 or later

System.Exception: 1168
   at Microsoft.Web.Administration.IisExpressServerManager.SetPassword(VirtualDirectory virtualDirectory, String password)
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password)
   at JexusManager.Dialogs.ConnectAsItem.Apply()
   at JexusManager.Dialogs.NewVirtualDirectoryDialog.<>c__DisplayClass0_1.<.ctor>b__3(EventPattern`1 evt)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value)

**Comment by lextm** [comment]
Duplicate to #136
