### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by anilghatol** [jexuswebserver/JexusManager#129]
13.0.0.21 on Windows 10 Enterprise (1809) with .NET Framework Version: 4.8 or later

System.Exception: -1 
   at Microsoft.Web.Administration.IisServerManager.SetPassword(VirtualDirectory virtualDirectory, String password)
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password)
   at JexusManager.Dialogs.ConnectAsItem.Apply()
   at JexusManager.Dialogs.NewApplicationDialog.<>c__DisplayClass2_1.<.ctor>b__3(EventPattern`1 evt)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value)

**Comment by lextm** [comment]
More information needed to be collected regarding such issues, and vNext will contain better logging.

**Comment by lextm** [comment]
Duplicate to #136
