### ISSUE TITLE
Error while adding application

### ISSUE THREAD

**Issue by asalhani** [jexuswebserver/JexusManager#131]
13.0.0.23 on Windows 10 Pro N (1903) with .NET Framework Version: 4.8 or later

System.Exception: 50 ERROR ( message:Must use exact identifer for VDIR object with verb SET. )

   at Microsoft.Web.Administration.IisExpressServerManager.SetPassword(VirtualDirectory virtualDirectory, String password)
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password)
   at JexusManager.Dialogs.ConnectAsItem.Apply()
   at JexusManager.Dialogs.NewApplicationDialog.<>c__DisplayClass2_1.<.ctor>b__3(EventPattern`1 evt)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value)

**Comment by asalhani** [comment]
[129](https://github.com/jexuswebserver/JexusManager/issues/129)
