### ISSUE TITLE
Unhandlled Exception

### ISSUE THREAD

**Issue by MicheleLC** [jexuswebserver/JexusManager#133]
13.0.0.24 on Windows 7 Professional (unknown) with .NET Framework Version: 4.8 or later

System.InvalidOperationException: menu item Edit Dynamic Restriction Settings... function Dynamic
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: null section
   at JexusManager.Services.ConfigurationService.GetSection(String sectionPath, String locationPath, Boolean acceptNonLocallyStored) in E:\JexusManager\JexusManager.Shared\Services\ConfigurationService.cs:line 90
   at JexusManager.Features.IpSecurity.IpSecurityFeature.Dynamic() in E:\JexusManager\JexusManager.Features.IpSecurity\IpSecurityFeature.cs:line 213
   at JexusManager.Features.IpSecurity.IpSecurityFeature.FeatureTaskList.Dynamic() in E:\JexusManager\JexusManager.Features.IpSecurity\IpSecurityFeature.cs:line 108
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.Web.Management.Client.TaskList.InvokeMethod(String methodName, Object userData) in E:\JexusManager\Microsoft.Web.Management\Client\TaskList.cs:line 23
   at JexusManager.Features.TaskItemExtensions.<>c__DisplayClass3_0.<TaskItemFill>b__0(Object o, EventArgs args) in E:\JexusManager\JexusManager.Shared\Features\TaskItemExtensions.cs:line 101
   --- End of inner exception stack trace ---
   at JexusManager.Features.TaskItemExtensions.<>c__DisplayClass3_0.<TaskItemFill>b__0(Object o, EventArgs args) in E:\JexusManager\JexusManager.Shared\Features\TaskItemExtensions.cs:line 101
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lextm** [comment]
Dynamic IP Restriction is an Out-of-band component so it requires extra installation, https://docs.microsoft.com/en-us/iis/manage/configuring-security/using-dynamic-ip-restrictions#getting-dynamic-ip-restrictions

Jexus Manager should detect whether it has been installed and show a more friendly error message.
