### ISSUE TITLE
Error while trying to set a user/password to access the physical path.

### ISSUE THREAD

**Issue by RealSvildr** [jexuswebserver/JexusManager#137]
13.0.0.28 on Windows 10 Pro (2009) with .NET Framework Version: 4.8 or later

System.Exception: -2146893802 VDIR object "WebSite1/" changed
ERROR ( hresult:80090016, message:Failed to commit configuration changes.  

Keyset does not exist

 )

   at Microsoft.Web.Administration.IisExpressServerManager.SetPassword(VirtualDirectory virtualDirectory, String password) in E:\company\JexusManager\Microsoft.Web.Administration\IisExpressServerManager.cs:line 164
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password) in E:\company\JexusManager\Microsoft.Web.Administration\VirtualDirectory.cs:line 68
   at JexusManager.Dialogs.ConnectAsItem.Apply() in E:\company\JexusManager\JexusManager\Dialogs\ConnectAsItem.cs:line 35
   at JexusManager.Dialogs.EditSiteDialog.<>c__DisplayClass1_0.<.ctor>b__5(EventPattern`1 evt) in E:\company\JexusManager\JexusManager\Dialogs\EditSiteDialog.cs:line 100
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54

**Comment by lextm** [comment]
Duplicate to #136
