### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by malbert69** [jexuswebserver/JexusManager#139]
13.0.0.20 on Windows 10 Pro (2004) with .NET Framework Version: 4.8 or later

System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Rectangle rect)
   at System.Windows.Forms.SplitContainer.RepaintSplitterRect()
   at System.Windows.Forms.SplitContainer.ResizeSplitContainer()
   at System.Windows.Forms.SplitContainer.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
