### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by thecodingboydotcom** [jexuswebserver/JexusManager#140]
13.0.0.28 on Windows 10 Pro (2009) with .NET Framework Version: 4.8 or later

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at JexusManager.DialogHelper.LoadCertificates(ComboBox comboBox, Byte[] hash, String store, IConfigurationService service) in E:\company\JexusManager\JexusManager.Shared\DialogHelper.cs:line 299
   at JexusManager.Dialogs.NewSiteDialog.NewSiteDialogLoad(Object sender, EventArgs e) in E:\company\JexusManager\JexusManager\Dialogs\NewSiteDialog.cs:line 298
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by lextm** [comment]
An incorrect error code was used to filter out exceptions, which caused this exception.

Fixed in 13.0.2.0 release.
