### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by RoyBradley** [jexuswebserver/JexusManager#144]
13.0.4.0 on Windows 10 Enterprise (2009) with .NET Framework Version: 4.8 or later

System.NullReferenceException: Object reference not set to an instance of an object.
   at JexusManager.Services.ConfigurationService.GetSection(String sectionPath, String locationPath, Boolean acceptNonLocallyStored) in E:\company\JexusManager\JexusManager.Shared\Services\ConfigurationService.cs:line 77
   at JexusManager.Features.DirectoryBrowse.DirectoryBrowseFeature.ApplyChanges() in E:\company\JexusManager\JexusManager.Features.DirectoryBrowse\DirectoryBrowseFeature.cs:line 165
   at JexusManager.Features.DirectoryBrowse.DirectoryBrowsePage.ApplyChanges() in E:\company\JexusManager\JexusManager.Features.DirectoryBrowse\DirectoryBrowsePage.cs:line 76
   at JexusManager.Services.NavigationService.NavigateToItem(NavigationItem item, Boolean initializing) in E:\company\JexusManager\JexusManager\Services\NavigationService.cs:line 53
   at JexusManager.MainForm.LoadPage(IModulePage page) in E:\company\JexusManager\JexusManager\MainForm.cs:line 388
   at JexusManager.Tree.SitesTreeNode.LoadPanels(MainForm mainForm, ServiceContainer serviceContainer, List`1 moduleProviders) in E:\company\JexusManager\JexusManager\Tree\SitesTreeNode.cs:line 64
   at JexusManager.MainForm.treeView1_AfterSelect(Object sender, TreeViewEventArgs e) in E:\company\JexusManager\JexusManager\MainForm.cs:line 673
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
