### ISSUE TITLE
Saving a Certificate to a Binding

### ISSUE THREAD

**Issue by chriswalpen** [jexuswebserver/JexusManager#145]
13.0.8.0 on Windows 10 Pro (2009) with .NET Framework Version: 4.8 or later

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualBasic.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'Microsoft.VisualBasic.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at JexusManager.StringUtility.MatchHostName(String name, String host)
   at Microsoft.Web.Administration.BindingUtility.MatchHostName(X509Certificate2 certificate, String host) in C:\Users\lextudio\source\repos\JexusManager\JexusManager.Shared\BindingUtility.cs:line 457
   at Microsoft.Web.Administration.BindingUtility.FixCertificateMapping(Binding binding, X509Certificate2 certificate2) in C:\Users\lextudio\source\repos\JexusManager\JexusManager.Shared\BindingUtility.cs:line 62
   at JexusManager.Features.Main.BindingDialog.<>c__DisplayClass0_0.<.ctor>b__1(EventPattern`1 evt) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Features\Main\BindingDialog.cs:line 175
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs:line 117

**Comment by lextm** [comment]
Seems to be version specific issue and not reported frequent with newer releases.

Close it now as no immediate action to investigate. Will rework on it if new reports come.
