### ISSUE TITLE
crash, please help, thanks

### ISSUE THREAD

**Issue by philipmonday** [jexuswebserver/JexusManager#146]
13.0.8.0 on Windows 10 Home (2009) with .NET Framework Version: 4.8 or later

System.Exception: -1 
   at Microsoft.Web.Administration.IisExpressServerManager.SetPassword(VirtualDirectory virtualDirectory, String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\IisExpressServerManager.cs:line 122
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\VirtualDirectory.cs:line 68
   at JexusManager.Dialogs.ConnectAsItem.Apply() in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\ConnectAsItem.cs:line 38
   at JexusManager.Dialogs.NewSiteDialog.<>c__DisplayClass0_1.<.ctor>b__4(EventPattern`1 evt) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\NewSiteDialog.cs:line 198
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
Duplicate to #169
