### ISSUE TITLE
Exception on setting "Require SNI"

### ISSUE THREAD

**Issue by DarthSonic** [jexuswebserver/JexusManager#147]
13.0.8.0 on Windows 10 Pro (2009) with .NET Framework Version: 4.8 or later

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualBasic.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
File name: 'Microsoft.VisualBasic.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at JexusManager.StringUtility.MatchHostName(String name, String host)
   at Microsoft.Web.Administration.BindingUtility.FixCertificateMapping(Binding binding, X509Certificate2 certificate2) in C:\Users\lextudio\source\repos\JexusManager\JexusManager.Shared\BindingUtility.cs:line 62
   at JexusManager.Features.Main.BindingDialog.<>c__DisplayClass0_0.<.ctor>b__1(EventPattern`1 evt) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Features\Main\BindingDialog.cs:line 175
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54

**Comment by lextm** [comment]
Duplicate to #145. Seems to be version specific issue and not reported frequent with newer releases.
