### ISSUE TITLE
HTTP API Error

### ISSUE THREAD

**Issue by lukandroll** [jexuswebserver/JexusManager#149]
I have VS 2017 & IIS Express installed, and this happens when I try to open HTTP API

13.0.8.0 on Windows 10 Enterprise (2009) with .NET Framework Version: 4.8 or later

System.NullReferenceException: Object reference not set to an instance of an object.
   at JexusManager.Features.HttpApi.HttpApiPage.TabControl1SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\lextudio\source\repos\JexusManager\JexusManager.Features.HttpApi\HttpApiPage.cs:line 292
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
