### ISSUE TITLE
exception setting up IIExpress

### ISSUE THREAD

**Issue by profK** [jexuswebserver/JexusManager#151]
13.0.10.0 on Windows 10 Education (2009) with .NET Framework Version: 4.8 or later

System.Exception: 1168 ERROR ( message:Configuration error 

Filename: \\?\U:\Personal\IISExpress\config\applicationhost.config

Line Number: 0

Description: Cannot read configuration file

. )

   at Microsoft.Web.Administration.IisExpressServerManager.SetPassword(VirtualDirectory virtualDirectory, String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\IisExpressServerManager.cs:line 122
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\VirtualDirectory.cs:line 68
   at JexusManager.Dialogs.ConnectAsItem.Apply() in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\ConnectAsItem.cs:line 38
   at JexusManager.Dialogs.NewSiteDialog.<>c__DisplayClass0_1.<.ctor>b__4(EventPattern`1 evt) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\NewSiteDialog.cs:line 198
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs:line 117
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by lextm** [comment]
No plan to support moved home folder to another drive or shared drive or OneDrive right now.

Pull requests are welcome.
