### ISSUE TITLE
Getting an error creating a virtual folder

### ISSUE THREAD

**Issue by starlisa** [jexuswebserver/JexusManager#158]
13.0.23.0 on Windows 10 Home (2009) X64

System.Exception: 1168 ERROR ( message:Configuration error 

Filename: \\?\C:\Users\user\Documents\IISExpress\config\applicationhost.config

Line Number: 156

Description: Cannot add duplicate collection entry of type 'site' with unique key attributes 'name, id' respectively set to 'KC, 1'

. )

   at Microsoft.Web.Administration.IisExpressServerManager.SetPassword(VirtualDirectory virtualDirectory, String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\IisExpressServerManager.cs:line 121
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\VirtualDirectory.cs:line 68
   at JexusManager.Dialogs.ConnectAsItem.Apply() in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\ConnectAsItem.cs:line 38
   at JexusManager.Dialogs.NewVirtualDirectoryDialog.<>c__DisplayClass0_1.<.ctor>b__3(EventPattern`1 evt) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\NewVirtualDirectoryDialog.cs:line 134
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs:line 117
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by lextm** [comment]
When you open `C:\Users\user\Documents\IISExpress\config\applicationhost.config` in notepad, can you observe duplicate `<site>` tags with their `name` and `id` values duplicate to each other?

**Comment by starlisa** [comment]
No, I cannot.  Here's the file for you to see.
[applicationhost.config.txt](https://github.com/jexuswebserver/JexusManager/files/12548135/applicationhost.config.txt)
