### ISSUE TITLE
Error Adding a web site definition

### ISSUE THREAD

**Issue by GuillaumeAndCo** [jexuswebserver/JexusManager#159]
13.0.23.0 on Windows 10 Enterprise (2009) X64

System.Exception: -3 
   at Microsoft.Web.Administration.IisExpressServerManager.SetPassword(VirtualDirectory virtualDirectory, String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\IisExpressServerManager.cs:line 121
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\VirtualDirectory.cs:line 68
   at JexusManager.Dialogs.ConnectAsItem.Apply() in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\ConnectAsItem.cs:line 38
   at JexusManager.Dialogs.NewSiteDialog.<>c__DisplayClass0_1.<.ctor>b__4(EventPattern`1 evt) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\NewSiteDialog.cs:line 214
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs:line 117
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
