### ISSUE TITLE
unhandled

### ISSUE THREAD

**Issue by Bezaleel2000** [jexuswebserver/JexusManager#160]
13.0.23.0 on Windows 10 Pro (1909) X64

System.UnauthorizedAccessException: Access to the path 'c:\Users\Beez\Documents\My Videos' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at JexusManager.Tree.ManagerTreeNode.LoadChildren(Application rootApp, Int32 rootLevel, String rootFolder, String pathToSite, ContextMenuStrip phyMenu, ContextMenuStrip vDirMenu, ContextMenuStrip appMenu) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Tree\ManagerTreeNode.cs:line 69
   at JexusManager.Tree.PhysicalDirectoryTreeNode.Expand(MainForm mainForm) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Tree\PhysicalDirectoryTreeNode.cs:line 119
   at JexusManager.MainForm.treeView1_BeforeExpand(Object sender, TreeViewCancelEventArgs e) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\MainForm.cs:line 1167
   at System.Windows.Forms.TreeView.TvnExpanding(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.
