### ISSUE TITLE
Exception creating IIS application

### ISSUE THREAD

**Issue by MalcolmEllis** [jexuswebserver/JexusManager#161]
Is actually Windows 11...

13.0.23.0 on Windows 10 Pro (2009) X64

System.Exception: -3 
   at Microsoft.Web.Administration.IisServerManager.SetPassword(VirtualDirectory virtualDirectory, String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\IisServerManager.cs:line 255
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password) in C:\Users\lextudio\source\repos\JexusManager\Microsoft.Web.Administration\VirtualDirectory.cs:line 68
   at JexusManager.Dialogs.ConnectAsItem.Apply() in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\ConnectAsItem.cs:line 38
   at JexusManager.Dialogs.NewApplicationDialog.<>c__DisplayClass2_1.<.ctor>b__3(EventPattern`1 evt) in C:\Users\lextudio\source\repos\JexusManager\JexusManager\Dialogs\NewApplicationDialog.cs:line 135
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by lextm** [comment]
Duplicate to #169
