### ISSUE TITLE
Error adding Virtual Directory

### ISSUE THREAD

**Issue by Disflippant** [jexuswebserver/JexusManager#167]
13.0.24.0 on Windows 10 Pro (2009) X64

System.Exception: -3 
   at Microsoft.Web.Administration.IisServerManager.SetPassword(VirtualDirectory virtualDirectory, String password) in C:\shared\jexusmanager\Microsoft.Web.Administration\IisServerManager.cs:line 255
   at Microsoft.Web.Administration.VirtualDirectory.SetPassword(String password) in C:\shared\jexusmanager\Microsoft.Web.Administration\VirtualDirectory.cs:line 68
   at JexusManager.Dialogs.ConnectAsItem.Apply() in C:\shared\jexusmanager\JexusManager\Dialogs\ConnectAsItem.cs:line 38
   at JexusManager.Dialogs.NewVirtualDirectoryDialog.<>c__DisplayClass0_1.<.ctor>b__4(EventPattern`1 evt) in C:\shared\jexusmanager\JexusManager\Dialogs\NewVirtualDirectoryDialog.cs:line 157
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by lextm** [comment]
Duplicate to #169
