### ISSUE TITLE
exus installation issue

### ISSUE THREAD

**Issue by sscott008** [jexuswebserver/JexusManager#168]
13.0.24.0 on Windows 10 Home (2009) X64

System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Jexus Manager\Jexus Manager\lists' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at JexusManager.DialogHelper.GetSpecialFolder(String name, String file) in C:\shared\jexusmanager\JexusManager.Shared\DialogHelper.cs:line 343
   at JexusManager.DialogHelper.get_ListIisExpress() in C:\shared\jexusmanager\JexusManager.Shared\DialogHelper.cs:line 359
   at JexusManager.MainForm.LoadIisExpress() in C:\shared\jexusmanager\JexusManager\MainForm.cs:line 244
   at JexusManager.MainForm..ctor(List`1 files) in C:\shared\jexusmanager\JexusManager\MainForm.cs:line 155
   at JexusManager.Program.Main(String[] args) in C:\shared\jexusmanager\JexusManager\Program.cs:line 87

**Comment by lextm** [comment]
Related to #118. The code itself tried to use the user folder to store its configuration files, but failed. The common cause is that you have moved that folder to elsewhere.
